language: python
# Test matrix
python:
    - 2.7
    - 3.2
    - 3.4
env:
    - DJANGO_VERSION=Django==1.7
# Services
services:
  - redis-server
  - elasticsearch
# Package installation
install:
  - python setup.py install
  - pip install psycopg2 elasticsearch
# Pre-test configuration
before_script:
  - psql -c 'create database wagtailforums_demo;' -U postgres
# Run the tests
script:
  python runtests.py
# Who to notify about build results
notifications:
  email:
    recipients:
      - karlhobley10@gmail.com
    on_success: change
    on_failure: always
